# no need to use sudo
sudo: false

language: node_js

node_js:
  - 7
  - 6

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn

script:
  - npm run ci:eslint
